### ISSUE TITLE
Accessibility: Display correct Stream Deck model button layout

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion#1352]
**Describe the feature**
Display the correct layout with the appropriate number of buttons (6, 15, or 32) under **Buttons** based on the connected Stream Deck model.

Don't know if this is a bug or the way I have it setup...
But Companion **always** displays 32 buttons! Why? I am visually impaired and would prefer to deal with only 15 buttons at a time, because that's the Stream Deck model I'm using. The extra buttons are an accessibility issue for me. I use Stylus to add the following CSS to remove the buttons (do I *really* need to do this, or is there some other reason that "emulator" is the first in my list of Surfaces, followed by my actual Stream Deck, and there are no settings to customize the emulator layout that I can tell?):
```css
#pagebank .bank {
    width: 20% !important;
}
#pagebank .bank:nth-child(8n) {
    display: none !important;
}
#pagebank .bank:nth-child(8n-1) {
    display: none !important;
}
#pagebank .bank:nth-child(8n-2) {
    display: none !important;
}
#pagebank .bank:nth-child(n+24) {
    display: none !important;
}
```

**I tried stopping/restarting the server, deleting the database files, etc. to no avail.**

**Is this platform dependent (windows, mac, ..)?**
Mac OS Catalina. I don't know about others.

**If documentation is required to implement, do you know where to find it?**
See CSS above. I am not familiar with the code/framework of this app.

**Usecases**
Well, there are currently (as of this writing) 3 models of Stream Deck:
- 6-button
- 15-button
- 32-button

Would be better UX for the UI to display the correct number of buttons.
