### ISSUE TITLE
[BUG] Add by category/manufacturer menus longer than page and don't scroll

### ISSUE THREAD

**Issue by tgrushka** [bitfocus/companion#1353]
**Build: v2.1.2**

**Describe the bug**
"Add by category" and "Add by manufacturer" dropdown menus run off the page and don't scroll properly unless the screen resolution is really, really high or the browser magnification is below 100%.

**To Reproduce**
Sorry guys that I'm creating another issue so soon. Just started using this app yesterday.
Tried this in both Chrome and Safari on MacOS.
Because I'm visually impaired, I typically run my screen at hi-DPI 1600x900 on a 4K monitor (magnification is crisp and awesome!).
**However, I also tried this at 3840x2160 with the same result.**
With either browser (Chrome or Safari) at default 100% magnification, I cannot see the whole list of categories (except at 3840x2160) and manufacturers (at any resolution), as they both run off the screen.
When trying to scroll down, the menus get all jittery and seem to be locked in the same position. Therefore, it is impossible to access any categories or manufacturers past the first few letters of the alphabet.
In the following screenshot, my Chrome magnification is set to 33%:
![image](https://user-images.githubusercontent.com/40548478/103426520-483bc480-4b77-11eb-920e-47bf2e06c246.png)

**Expected behavior**
I should be able to scroll the dropdown menus so that I can access all of the options.

**Screenshots**
![image](https://user-images.githubusercontent.com/40548478/103426407-8b496800-4b76-11eb-9bff-1ca1a6ca6182.png)
![image](https://user-images.githubusercontent.com/40548478/103426412-98feed80-4b76-11eb-9a56-6cc4e903476a.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome & Safari
 - Companion Version 2.1.2

**Additional context**
I am able to work around this issue by adding the following CSS to my Stylus config for Companion (which limits the height of the menus and allows them to be scrolled with the wheel):
```css
.dropdown-menu {
    overflow-y: scroll;
    max-height: 80vh !important;
}
```
There is probably a better way to do this using JavaScript in the UI framework but this works for me for now.

**Comment by tgrushka** [comment]
Wait a minute... my workaround doesn't actually work... the sub-menus don't show up. Working on it...

**Comment by josephdadams** [comment]
This has been reported many times. I’m feeling too lazy to link it to a duplicate but still open issue, but it’s out there. Most people just use the search.

**Comment by FrancoJim** [comment]
Something that worked for me. 

```css
.dropdown-menu {
	overflow-y: scroll;
	max-height: 80vh;
	overflow-x: hidden;
	z-index: 1;
	/* Sit on top */
	transition: 0.5s;
	/* 0.5 second transition effect to slide in or slide down the overlay (height or width, depending on reveal) */
}
.dropdown-menu:hover {
	display: inline-table;
	z-index: 1;
	transition: 0.5s;
	/* 0.5 second transition effect to slide in or slide down the overlay (height or width, depending on reveal) */
}
```

**Comment by FrancoJim** [comment]
Another rendition that works better. It looks a bit janky, but I'm not very good with CSS. 
```css
.dropdown-menu {
	position: relative !important;
	overflow: auto !important;
	max-height: 80vh;
	overflow-x: hidden;
	z-index: 1;
	transition: 0.5s;
	transform: translate3d(-15%, -10%, 0px) !important;
	width: auto !important;
}
.dropdown-menu:hover {
	display: inline-table;
	position: relative !important;
}
```
