### ISSUE TITLE
[BUG] Docker: wrong directory after local module installation

### ISSUE THREAD

**Issue by fmalcher** [bitfocus/companion#2163]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `Dockerfile`'s entrypoint is the [installation script for modules](https://github.com/bitfocus/companion/blob/master/module-dev-docker-entrypoint.sh). This script changes the working directory  to the module directory:

```bash
cd /app/module-local-dev/$module
```

After this, running the Companion start command fails – *we are in the wrong directory!*

```
/app/module-dev-docker-entrypoint.sh: line 19: /app/module-local-dev/companion-module-foobar/headless_ip.js: No such file or directory
```

### Possible solution

The script has to change back to the `/app` dir before trying to start companion.
It works when I add the following line in [module-dev-docker-entrypoint.sh](https://github.com/bitfocus/companion/blob/master/module-dev-docker-entrypoint.sh#L18), line 18:

```bash
cd /app
```

**Can anybody reproduce this and confirm that the `cd` command is the right approach?**

### Steps To Reproduce

- Clone the companion repo
- use the following simple `docker-compose.yml` outside the `companion` folder to build and start:

```yml
version: "3"
services:
  companion:
    build: ./companion
    ports:
      - 8000:8000
    volumes:
      - ./config:/companion
      - ./module-local-dev:/app/module-local-dev
```

- Put a module into `module-local-dev` (bind mount outside the container)
- `docker compose up`
- Run into the error!

### Environment (please complete the following information)

```markdown
- OS: macOS 13.0
- Companion Version: 2.3.1
- Docker: Docker version 20.10.10, build b485636
```
